# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b344573c76fe4691ed56cd7a58a5c09d099c3f380daff8d7217069feca9d4e6a9448fd159fb13a50994159d18e634ea8a23ffb31185da048d6339b779bba26

test:
  secret_key_base: a7403ba93175ca229a7ba938b54ce1013664fd9fa3746a014cf06389cd00420a9fa921c5a4d5e5d7c995f6819f3872e93095c9f6a074f9607fa30fa75f492771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
